### 1. Login and set cookies
POST http://127.0.0.1:8000/accounts/api/token/
Content-Type: application/json

{
    "username":"yu123",
    "password":"#20050523#"
}

### 2. Call AI endpoint (replace <your_token> with actual token)
POST http://127.0.0.1:8000/concour/ai/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU4OTM5NTc5LCJpYXQiOjE3NTg5Mzg2NzksImp0aSI6ImIyYTZkN2UyMTgzNTRjNDQ4Y2YxODQ0NTI1MzIyY2ZkIiwidXNlcl9pZCI6IjEifQ.0-pPhPjrUpQZXjdA4-8TLBsD3k5yW31ofyZGyzWklS8

{
    "prompt" : "what is AI ?"
}