# Generated by Django 5.2.5 on 2025-08-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
