# Generated by Django 5.2.5 on 2025-08-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0002_level_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='university',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='year',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
