# Generated by Django 5.2.5 on 2025-08-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0003_concours_slug_subject_slug_university_slug_year_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='subject',
        ),
        migrations.AddField(
            model_name='score',
            name='concours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='concour.concours'),
        ),
    ]
