# Generated by Django 5.2.5 on 2025-08-27 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0004_remove_score_subject_score_concours'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='concours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='concour.concours'),
        ),
    ]
