# Generated by Django 5.2.5 on 2025-08-27 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0005_useranswer_concours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='concours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='useranswer', to='concour.concours'),
        ),
    ]
