# Generated by Django 5.2.5 on 2025-08-28 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0008_remove_score_user_answers_useranswer_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers_score', to='concour.score'),
        ),
    ]
