# Generated by Django 5.1.3 on 2025-09-09 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0009_alter_useranswer_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
    ]
