# Generated by Django 5.1.3 on 2025-09-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0010_rename_text_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='type',
            field=models.CharField(choices=[('entrainement', 'Entrainement'), ('examen', 'Examen'), ('correction', 'Correction')], default='entrainement', max_length=30),
        ),
    ]
