# Generated by Django 5.1.3 on 2025-09-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0011_alter_score_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='type',
        ),
    ]
