# Generated by Django 5.1.3 on 2025-09-22 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0012_remove_score_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='choice',
            new_name='user_choice',
        ),
    ]
