# Generated by Django 5.2.6 on 2025-10-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0013_rename_choice_useranswer_user_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concours',
            name='timer',
        ),
    ]
