# Generated by Django 5.2.6 on 2025-10-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0014_remove_concours_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='concours',
            name='timer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
