# Generated by Django 5.2.6 on 2025-10-10 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0015_concours_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers_choice', to='concour.choice'),
        ),
    ]
