# Generated by Django 5.2.6 on 2025-10-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0017_alter_useranswer_user_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='incorrect_answer_count',
            field=models.IntegerField(default=0),
        ),
    ]
