# Generated by Django 5.2.6 on 2025-10-18 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0019_alter_question_options_question_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='incorrect_answer_count',
        ),
    ]
