# Generated by Django 5.2.6 on 2025-10-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0020_remove_useranswer_incorrect_answer_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
    ]
