# Generated by Django 5.2.6 on 2025-10-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0021_alter_year_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course_parts',
        ),
        migrations.AddField(
            model_name='question',
            name='context_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
