# Generated by Django 5.2.6 on 2025-10-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0022_remove_question_course_parts_question_context_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePart',
        ),
    ]
