# Generated by Django 5.2.6 on 2025-10-21 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0023_delete_coursepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='context_text',
        ),
        migrations.AddField(
            model_name='question',
            name='exercice_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='concour.exercicecontext'),
        ),
    ]
