# Generated by Django 5.2.6 on 2025-10-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0025_alter_question_options_question_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_order_per_concours',
        ),
    ]
