# Generated by Django 5.2.6 on 2025-10-22 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0026_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
