# Generated by Django 5.2.6 on 2025-10-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0027_remove_question_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
