# Generated by Django 5.2.6 on 2025-10-28 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0028_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciceContextImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exercice_context_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('concours', 'order'), name='unique_order_per_concours'),
        ),
        migrations.AddField(
            model_name='exercicecontextimage',
            name='exercice_context',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='concour.exercicecontext'),
        ),
    ]
