# Generated by Django 5.2.6 on 2025-10-31 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0029_exercicecontextimage_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='level',
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
