# Generated by Django 5.2.6 on 2025-10-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0030_remove_university_level_delete_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='is_open',
        ),
    ]
