# Generated by Django 5.2.6 on 2025-11-01 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0031_remove_university_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicecontextimage',
            name='uploaded_at',
        ),
    ]
