# Generated by Django 5.2.6 on 2025-11-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0032_remove_exercicecontextimage_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
    ]
