# Generated by Django 5.2.8 on 2025-11-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0035_alter_exercicecontext_hex_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicecontext',
            name='hex_color',
            field=models.CharField(choices=[('#FF6B6B', 'Red'), ('#4ECDC4', 'Teal'), ('#45B7D1', 'Blue'), ('#96CEB4', 'Green'), ('#FECA57', 'Yellow'), ('#FF9FF3', 'Pink'), ('#54A0FF', 'Light Blue'), ('#5F27CD', 'Purple'), ('#00D2D3', 'Cyan'), ('#FF9F43', 'Orange'), ('#10AC84', 'Dark Green'), ('#EE5A24', 'Dark Orange'), ('#0984E3', 'Dark Blue'), ('#6C5CE7', 'Light Purple'), ('#A29BFE', 'Lavender'), ('#FD79A8', 'Hot Pink'), ('#E17055', 'Coral'), ('#81ECEC', 'Light Cyan'), ('#74B9FF', 'Sky Blue'), ('#A0E7E5', 'Mint Green')], default='#FF6B6B', help_text='Hex color code for the exercise context', max_length=7),
        ),
        migrations.AddConstraint(
            model_name='exercicecontext',
            constraint=models.UniqueConstraint(condition=models.Q(('questions__isnull', False)), fields=('hex_color',), name='unique_color_per_concours'),
        ),
    ]
