# Generated by Django 5.2.8 on 2025-11-21 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concour', '0036_alter_exercicecontext_hex_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exercicecontext',
            name='unique_color_per_concours',
        ),
    ]
